spring.application.name=FinApp
# Spring Boot automatically pulls these from your system environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Tell Spring Boot to use the PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update tables based on your Java entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL in the console (helpful for debugging)
spring.jpa.show-sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970