spring.application.name=FinApp

spring.profiles.active=dev

# Spring Boot automatically pulls these from your system environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Tell Spring Boot to use the PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update tables based on your Java entities
spring.jpa.hibernate.ddl-auto=update


jwt.secret=${JWT_SECRET}
cors.allowed.origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}

# SpringDoc config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.forward-headers-strategy=framework